### ISSUE TITLE
Feature request: Clone Adom

### ISSUE THREAD

**Issue by moustic999** [realvitya/pyfortinet#3]
We are currently building an autmoated provisioning tool and the first basic task we need is to clone our main Adom which contains a basic set of config and templates.

By supporting the clone adom, we could use this library and extend it to our needs. I will also provide pull request with new features.

**Comment by viktorkertesz** [comment]
Currently there is no ADOM related class. I'm confused, you want to develop it?

**Comment by moustic999** [comment]
as you say, there is no ADOM class, but you already handle some adoms methods, like lock, unlock, commit.
The clone adom is special as you have to lock the original adom, then clone it with a new name. 
Sur sure how and where to implement it.

**Comment by viktorkertesz** [comment]
Ok, I'll work on .clone method and I try to add ADOM manipulation too. Give me some time to work on it..

**Comment by realvitya** [comment]
I checked API docs:

> Device Manager Database Objects Reference
> 
> adom (table)
> ADOM table, most attributes are read-only and can only be changed internally.
> 
> Supported methods: [get (table)](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#get-table), [get (object)](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#get-obj), [get (auxiliary)](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#get-table-aux), [add](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#add), [add (member)](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#add-member), [set](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#set), [set (member)](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#set-member), [update](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#update), [update (member)](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#update-member), [delete](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#delete), [delete (member)](https://github.com/realvitya/pyfortinet/issues/dvmdb-methods.htm#delete-member)

No clone method. And then I found this forum entry: https://fndn.fortinet.net/index.php?/stackoverflow/topic/854-fmg-api-clone-adom/&tab=comments#comment-3577
So it is possible. I plan to make and ADOM class with all info and an ADOMClone task that will create a task which you can wait for. I can also try to create a general `.clone()` method, but I need to do testing to make it work for all supported objects.

**Comment by realvitya** [comment]
@moustic999 may I ask you to test the ADOM cloning from this branch? https://github.com/realvitya/pyfortinet/tree/adom
Unfortunately I cannot test in my virtual lab as it complains about lack of license. I'll do more testing in my real lab on weekdays.
Example code is in `tests/fmg/objects/test_dvmdb.py`

So cloning empty ADOMs work. But when I tried to clone an ADOM with data, it did not. Please test on a real FMG till I can. Thanks!

**Comment by realvitya** [comment]
Feature added, will be part of next release
