### ISSUE TITLE
Feature Request : add a model device without SN but with psk

### ISSUE THREAD

**Issue by moustic999** [realvitya/pyfortinet#4]
Fortimanager api support adding model device without SN but with a PSK and a valid Platform_str; We use this a lot to provision our Fortigates; Would be great to have this supported as we never know the SN of the device which will be installed.

**Comment by viktorkertesz** [comment]
Hi @moustic999,
I am not sure I wanna keep `ModelDevice` and `RealDevice` nor `BaseDevice`. Can you try creating [Device](https://realvitya.github.io/pyfortinet/reference/fmg_api/dvmdb/#fmg_api.dvmdb.Device) object? It has the necessary `psk` and `platform_str` field and also SN is not mandatory.

I forgot to extend `ModelDevice `with all fields and focused on `Device`.
Original idea with `ModelDevice` was to distinguish mandatory fields like `version` and `mr` (minor release). But I am thinking of getting rid of them. Do you have any opinion on that one? Problem with FMG is the error feedback is not very helpful most of the time and I wanted to make developers' life easier not to allow things which would end up with an error like "Invalid data". I found that confusing sometimes.

**Comment by realvitya** [comment]
Feature added, will be part of next release
